In [46]:
import pandas as pd

In [59]:
df = pd.read_excel("./BerkData.xlsx")
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Bilgisayar Mühendisliği,CSE 214,Advanced Application Development,6,4,0,2,3,2,Z,3435711,26
1,Bilgisayar Mühendisliği,CSE 214,Advanced Application Development,6,4,0,2,3,2,Z,3435711,40
2,Bilgisayar Mühendisliği,CSE 336,Advanced Web Programming,6,4,0,3,3,1,S,2107934,12
3,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,4,3,0,2,2,1,Z,3048102,125
4,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,5,3,0,2,2,1,Z,1098471,7
...,...,...,...,...,...,...,...,...,...,...,...,...
467,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,5,3,0,4,2,1,Z,5997408,9
468,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,5,3,0,4,2,1,S,3524624,15
469,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,5,4,0,3,3,1,Z,1892200,2
470,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,5,4,0,3,3,1,Z,1892200,5
471,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,5,3,0,3,2,1,S,2977082,52

In [60]:
for dep1 in df["DepartmentName"].unique():
    print(f"====== Department_1: {dep1} =======")
    dep1_courses = df[df["DepartmentName"] == dep1]["CourseCode"]
    dep1_set = set(dep1_courses)
    for dep2 in df["DepartmentName"].unique():
        if dep1 != dep2:
            print("=============")
            print(f"Department_1: {dep1} vs. Department_2: {dep2}")
            dep2_courses = df[df["DepartmentName"] == dep2]["CourseCode"]
            dep2_set = set(dep2_courses)
            print(dep1_set.intersection(dep2_set))

====== Department_1: Bilgisayar Mühendisliği =======
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'KPD 102', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'TDB 102', 'HOBİ 108'}
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: Gıda Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'KPD 102', 'PFE 204'}
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 304', 'PFE 302', 'MAT 152', 'PFE 202', 'FİZ 174', 'FİZ 176', 'PFE 204'}
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: Bilgisayar Mühendisliği vs. Department_2: Çevre Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102', 'MAT 152'}
====== Department_1: İnşaat Mühendisliği =======
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'KPD 102', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'İNM 108', 'JEO 308', 'TDB 102', 'YBD 102', 'MAT 162', 'HOBİ 108'}
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Gıda Mühendisliği
{'ATA 102', 'FİZ 168', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'KPD 102', 'MAT 162', 'PFE 204'}
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204'}
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'MAT 162', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: İnşaat Mühendisliği vs. Department_2: Çevre Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102'}
====== Department_1: Jeoloji Mühendisliği =======
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'ATA 102', 'TDB 102', 'HOBİ 108'}
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'ATA 102', 'İNM 108', 'JEO 308', 'TDB 102', 'YBD 102', 'MAT 162', 'HOBİ 108'}
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: Gıda Mühendisliği
{'ATA 102', 'TDB 102', 'MAT 162', 'YBD 102'}
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102'}
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102', 'YBD 102', 'MAT 162', 'HOBİ 108'}
=============
Department_1: Jeoloji Mühendisliği vs. Department_2: Çevre Mühendisliği
{'ATA 102', 'TDB 102', 'ÇEV 202'}
====== Department_1: Gıda Mühendisliği =======
=============
Department_1: Gıda Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'KPD 102', 'PFE 204'}
=============
Department_1: Gıda Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'ATA 102', 'FİZ 168', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'KPD 102', 'MAT 162', 'PFE 204'}
=============
Department_1: Gıda Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'TDB 102', 'MAT 162', 'YBD 102'}
=============
Department_1: Gıda Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204'}
=============
Department_1: Gıda Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'MAT 162', 'PFE 204'}
=============
Department_1: Gıda Mühendisliği vs. Department_2: Çevre Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102'}
====== Department_1: Elektrik-Elektronik Mühendisliği =======
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 304', 'PFE 302', 'MAT 152', 'PFE 202', 'FİZ 174', 'FİZ 176', 'PFE 204'}
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204'}
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'TDB 102'}
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: Gıda Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204'}
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102', 'EEM 350', 'PFE 302', 'PFE 202', 'PFE 204', 'EEM 204'}
=============
Department_1: Elektrik-Elektronik Mühendisliği vs. Department_2: Çevre Mühendisliği
{'ATA 102', 'TDB 102', 'MAT 152'}
====== Department_1: Makine Mühendisliği =======
=============
Department_1: Makine Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'PFE 202', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: Makine Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'MAT 162', 'PFE 204', 'HOBİ 122', 'HOBİ 108'}
=============
Department_1: Makine Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'TDB 102', 'YBD 102', 'MAT 162', 'HOBİ 108'}
=============
Department_1: Makine Mühendisliği vs. Department_2: Gıda Mühendisliği
{'ATA 102', 'TDB 102', 'PFE 302', 'YBD 102', 'PFE 202', 'MAT 162', 'PFE 204'}
=============
Department_1: Makine Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102', 'EEM 350', 'PFE 302', 'PFE 202', 'PFE 204', 'EEM 204'}
=============
Department_1: Makine Mühendisliği vs. Department_2: Çevre Mühendisliği
{'ATA 102', 'TDB 102'}
====== Department_1: Çevre Mühendisliği =======
=============
Department_1: Çevre Mühendisliği vs. Department_2: Bilgisayar Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102', 'MAT 152'}
=============
Department_1: Çevre Mühendisliği vs. Department_2: İnşaat Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102'}
=============
Department_1: Çevre Mühendisliği vs. Department_2: Jeoloji Mühendisliği
{'ATA 102', 'TDB 102', 'ÇEV 202'}
=============
Department_1: Çevre Mühendisliği vs. Department_2: Gıda Mühendisliği
{'KPD 102', 'ATA 102', 'TDB 102'}
=============
Department_1: Çevre Mühendisliği vs. Department_2: Elektrik-Elektronik Mühendisliği
{'ATA 102', 'TDB 102', 'MAT 152'}
=============
Department_1: Çevre Mühendisliği vs. Department_2: Makine Mühendisliği
{'ATA 102', 'TDB 102'}

In [61]:
deps = df["DepartmentName"].unique()

for dep in deps:
    codes = df[df["DepartmentName"] == dep]["CourseCode"].unique()
    for code in codes:
        # Filter the rows with the same DepartmentName and CourseCode
        courses = df[(df["DepartmentName"] == dep) & (df["CourseCode"] == code)]
        if len(courses) > 1:
            sum_count = courses["OgrenciSayisi"].sum()
            
            # Keep the first index, drop the rest
            keep_index = courses.index[0]
            drop_indices = courses.index[1:]
            
            df.loc[keep_index, "OgrenciSayisi"] = sum_count
            df.drop(drop_indices, inplace=True)

# Reset index if necessary
df.reset_index(drop=True, inplace=True)

In [62]:
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Bilgisayar Mühendisliği,CSE 214,Advanced Application Development,6,4,0,2,3,2,Z,3435711,66
1,Bilgisayar Mühendisliği,CSE 336,Advanced Web Programming,6,4,0,3,3,1,S,2107934,12
2,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,4,3,0,2,2,1,Z,3048102,125
3,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,5,3,0,2,2,1,Z,1098471,7
4,Gıda Mühendisliği,GIDA 224,Akışkanlar Mekaniği,5,3,0,2,3,0,Z,2061533,72
...,...,...,...,...,...,...,...,...,...,...,...,...
289,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,5,3,0,4,2,1,Z,5997408,9
290,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,5,3,0,4,2,1,S,3524624,15
291,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,5,4,0,3,3,1,Z,1892200,2
292,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,5,4,0,3,3,1,Z,1892200,5
293,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,5,3,0,3,2,1,S,2977082,52

In [63]:
df.to_excel("./BerkData2.xlsx")